# Generated by Django 3.1.2 on 2020-11-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imdbid', models.CharField(max_length=1024)),
                ('title', models.CharField(max_length=265)),
                ('overview', models.TextField()),
                ('genres', models.CharField(default='', max_length=265)),
                ('realeasedate', models.CharField(default='', max_length=128)),
                ('runningtime', models.PositiveSmallIntegerField()),
                ('language', models.CharField(default='', max_length=128)),
                ('image', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserMovieRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=128)),
                ('movie_id', models.CharField(max_length=128)),
                ('rating', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
    ]
